# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.2.0
_src_path: gh:jmineau/python-template
affiliation: University of Utah
copyright_year: '2026'
distribution_name: fips
docs_notebooks: true
email: jameskmineau@gmail.com
full_name: James Mineau
github_username: jmineau
orcid: 0000-0002-2289-2252
package_name: fips
project_name: fips
project_short_description: Flexible Inverse Problem Solver (FIPS)
publish_to_pypi: true
python_min: '3.11'
repository_name: fips
test_os:
- ubuntu-latest
- macos-latest
- windows-latest
